config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # トップページのルーティング
   root to: 'homes#top'
  # aboutページのルーティング
   get 'about' => 'homes#about'
# resourcesで必要なアクションとビューだけを用意する
   resources :users, only: [:index, :show, :edit, :update]
   # 「ネストする」ブックに対しての子要素となる
   resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # user_idに関連づけられる、userを参照できる
  belongs_to :user
  #1:nの関係bookとbook_commentとの関連付け。関連したbookが消されたらコメントも消える
  has_many :book_comments, dependent: :destroy
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  # 関連付けをするための記述、ユーザーとブックに紐付けを行う
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #1:nの関係userとbookとの関連付け。関連したuserが消されたらbookも消える
  has_many :books, dependent: :destroy
  # 画像アップ用のメソッド（attachment）を追加してフィールド名に（profile_image）を指定この時、idは抜く。※refileのルール
  attachment :profile_image
  #1:nの関係userとbook_commentとの関連付け。関連したuserが消されたらコメントも消える
  has_many :book_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

# サインインした後の遷移先の指定。resourceは形で覚える。テンプレートとして覚えてもおっけ。
  def after_sign_in_path_for(resource)
    # 今回でいえば、（）内はcurrent_userと同じ動作
    user_path(resource)
  end

  protected
# ストロングパラメータと同じ役割
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    # book_idのルートを確認すると、commentはbookに対してネストしているので、idの部分が特殊
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    # コメントテーブルのbook_idと投稿のidが一緒だよ
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book.id)
  end

  def destroy
    BookComment.find_by(id: params[:id],book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
# インスタンス変数とローカル変数の違い。色々あるけど、ビューに渡すか渡さないかだよ
    def create
        # 何を入れるのか。ストロングパラメーター,privateの（book_params）を入れないと、空のままviewに送ってしまう
        @book = Book.new(book_params)
        # 誰が投稿したのかを識別するために、idを指定
        @book.user_id = current_user.id
        @book.save
        redirect_to book_path(@book)
    end

    def index
        @user = current_user
        @book = Book.new
        @books = Book.all
    end

    def show
        @user = current_user
        @book = Book.new
        @books = Book.find(params[:id])
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        book = Book.find(params[:id])
        book.update(book_params)
        redirect_to book_path(book)
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    private

    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @users = User.find(params[:id])
    @book = Book.new
    # このように記述することで、そのユーザ（@users）に関連付けられた投稿のみ、@booksに渡すことができます。
    # 全体の投稿ではなく、個人が投稿したもののみを表示できます。
    @books = @users.books
                    # booksはテーブル名
  end

  def index
     @user = current_user
     @book = Book.new
     @users = User.all
  end

  def edit
    @user = current_user
    @book = Bool.find(params[:id])
  end

  def update
    @book = Book.(params[:id])
    @book = Book.update(book_params)
    redirect_to book_path(@book.id)
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new_form.html.erb
 <div class="col-md-3">
      <h2>ユーザー情報</h2>
      <!--プロフィールイメージを表示するためのコード。プロフィール画像を登録していない場合のfallbackもサイズ指定が必須-->
       <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100', class: "m-2 attachment user profile_image" %>
       <table class="table">
         <tbody>
           <tr></tr>
           <tr>
             <th class="text-white">名前</th>
             <th class="text-white"><%= user.name %></th>
           </tr>
           <tr>
             <th class="text-white">プロフィール</th>
             <th class="text-white"><%= user.introduction %></th>
           </tr>
         </tbody>
       </table>
       <div class="row">
         <%= link_to"",edit_user_path(user), class:"fas fa-user-cog btn btn-outline-light btn-block" %>
       </div>
      <h2 class="mt-3">新規投稿</h2>
      <!--新規投稿フォームの作成-->
      <%= form_with model:book, local:true do |f| %>
       <div class="form-group">
         <label>本の題名</label>
         <%= f.text_field :title %>
       </div>
       <div class="form-group">
         <label>本の感想</label>
         <%= f.text_area :body %>
       </div>
       <div class="form-group">
         <%= f.submit '投稿', class: "btn btn-success" %>
       </div>
       <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>編集ページ</h1>
      <%= form_with model:@book,local: true do |f| %>
        <div class="form-group">
         <label>本の題名</label><br>
         <%= f.text_field :title, class: "form-control book_title" %>
       </div>
        <div class="form-group">
         <label>本の感想</label><br>
         <%= f.text_area :body, class: "form-control book_body" %>
       </div>
        <div class="form-group">
         <%= f.submit '更新', class: "btn btn-success" %>
       </div>
      <% end %>
      <%= link_to"詳細", book_path(@book.id) %>
      |
      <%= link_to"一覧", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--部分テンプレート-->
    <%= render 'books/new_form', user: @user, book: @book %>
    <!--投稿一覧のコード-->
     <div class="col-md-8 offset-md-1">
       <h2>投稿一覧</h2>
       <table class="table table-hover table-inverse">
         <thead>
           <tr>
             <th></th>
             <th class="text-white">題名</th>
             <th class="text-white">感想</th>
             <th colspan="3"></th>
           </tr>
         </thead>
         <tbody><% @books.each do |book| %>
            <tr>
              <td>
                  <!--ユーザー画像はuser_showへのリンク-->
                <%= link_to user_path(book.user.id) do %>
              <!--eachで代入されたbookに関連づいたuserを表す-->
                 <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "m-2 attachment user profile_image" %>
                <% end %>
              </td>
              <!--タイトルはbook_showのリンク-->
              <td class="text-white"><%= link_to book.title,book_path(book.id) %></td>
              <td class="text-white"><%= book.body %></td>
            </tr>
            <% end %>
         </tbody>
       </table>
     </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--部分テンプレート-->
    <%= render 'books/new_form', user: @user, book: @book %>
    <!--投稿詳細のコード-->
     <div class="col-md-8 offset-md-1">
       <h2>投稿詳細</h2>
       <table class="table">
         <tbody>
           <tr>
             <td>
               <%= link_to user_path(@books.user.id) do %>
               <%= attachment_image_tag @books.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "m-2 attachment user profile_image" %>
               <% end %>
             </td>
             <td><%= link_to @books.title,book_path(@books) %></td>
             <td class="text-white"><%= @books.body %></td>
             <!--ログインしているユーザーのshowページだった場合表示される-->
             <% if @user.id == current_user.id %>
             <td><%= link_to "編集",edit_book_path(@books),class: "btn btn-info" %></td>
             <td><%= link_to "削除",book_path(@books),class: "btn btn-danger", method: :delete %></td>
             <% end %>
           </tr>
         </tbody>
       </table>
       <div class="border-bottom border-white"></div>
       <!--コメント作成機能-->
       <div class="comments">
         <h2 class="mt-3">新規投稿</h2>
      <!--コメント投稿フォームの作成-->
         <%= form_with(model:[@books, @book_comment],local: true) do |f| %>
       <div class="form-group">
         <%= f.text_area :comment, rows:'2',placeholder: "コメント" %>
       </div>
       <div class="form-group">
         <%= f.submit '投稿', class: "btn btn-success" %>
       </div>
       <% end %>
         <!--もし、コメントが無ければ、コメント無しとビューで表記し、あれば何個コメントがあるか表記するコード-->
         <% if @books.book_comments.count == 0 then %>
         <p>コメント無し</p>
         <% else %>
         <p>コメント件数:<%= @books.book_comments.count %></p>
         <table class="table">
           <thead>
             <tr>
               <th></th>
               <th class="text-white">コメント</th>
               <th colspan="2"></th>
             </tr>
           </thead>
           <tbody>
             <% @books.book_comments.each do |book_comment| %>
               <tr>
                 <td class="text-white">
                   <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "m-2 attachment user profile_image" %>
                   <br><%= book_comment.user.name %>
                 </td>
                 <td class="text-white"><%= book_comment.comment %></td>
                 <!--コメントの、投稿日時を呼び出すコード-->
                 <td class="text-white"><%= book_comment.created_at.strftime('%Y-%m-%d %M:%S') %></td>
                 <% if @user.id == current_user.id %>
                 <td> <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment),class: "btn btn-danger", method: :delete %></td>
                 <% else %>
                 <td></td>
                 <% end %>
               </tr>
             <% end %>
           </tbody>
          <% end %>
          </table>
        </div>
     </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="px-3">
        <h1>Welcome to <strong><i class="fas fa-book"></i>BOOKERS</strong> !!</h1>
        <p class="lead"><strong><i class="fas fa-book"></i>BOOKERS</strong>はたくさんの人と</p>
        <p class="lead">本の内容について意見交流ができます</p>
        <p class="lead">お気に入りの一冊が見つかるかもしれません</p>
        <p class="lead">素敵な本との出会いを求めて</p>
        <p class="lead">早速登録してみましょう</p>
</div>

app/views/homes/top.html.erb
  <div class="px-3">
        <h1>Welcome to <strong><i class="fas fa-book"></i>BOOKERS</strong> !!</h1>
        <p class="lead"><strong><i class="fas fa-book"></i>BOOKERS</strong>では</p>
        <p class="lead">本の題名や感想をみんなでシェアできます</p>
        <p class="lead">さあ、あなたも本の世界へ！！</p>
  <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-primary btn-lg" %>
  <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-success btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKERS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex h-100 text-center text-white bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <h3 class="float-md-start mb-0"><%= link_to "BOOKERS", root_path, class: "text-white" %></h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <% if user_signed_in? %>
            <%= link_to "ホーム", user_path(current_user), class: "nav-link text-white" %>
            <%= link_to "ユーザー一覧", users_path, class: "nav-link text-white" %>
            <%= link_to "投稿一覧", books_path, class: "nav-link text-white" %>
            <!--ログアウトページのコード-->
            <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link text-white", method: :delete %>
            <% else %>
            <%= link_to "ホーム", root_path, class: "nav-link text-white" %>
             <%= link_to "アバウト", about_path, class: "nav-link text-white" %>
             <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-white" %>
             <%= link_to "ログイン", new_user_session_path, class: "nav-link text-white" %>
            <% end %>
          </nav>
        </div>
      </header>
       <%= yield %>


      <footer class="mt-auto text-white-50">
        <p>Made in Yanagawa</p>
      </footer>
    </div>
   </body>

</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>ユーザー　編集</h2>
     <%= form_with model:@user, local:true do |f| %>
     <div class="form-group">
       <label for="inputName">名前</label><br>
       <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
     </div>
     <div class="form-group">
       <label for="inputImage">プロフィール画像</label>
       <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
     </div>
     <div class="form-group">
       <label for="inputName">プロフィール</label><br>
       <%= f.text_area :introduction, autofocus: true, id:"inputName", placeholder:"プロフィール"%>
     </div>
     <div class="form-group">
       <%= f.submit "変更を保存" %>
     </div>
     <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <!--プロフィールイメージを表示するためのコード。プロフィール画像を登録していない場合のfallbackもサイズ指定が必須-->
      <%= render 'books/new_form', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
     <h2>全ユーザー</h2>
     <table class="table">
         <thead>
             <tr>
                 <th class="text-white">ユーザー画像</th>
                 <th class="text-white">名前</th>
                 <th colspan="3"></th>
             </tr>
         </thead>
         <tbody>
            <% @users.each do |user| %>
             <tr>
                 <th>
                     <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "m-2 attachment user profile_image" %>
                 </th>
                 <th class="text-white">
                     <%= user.name %>
                 </th>
                 <th>
                     <%= link_to"詳細", user_path(user.id) %>
                 </th>
             </tr>
           <% end %>
         </tbody>
     </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>ユーザー情報</h2>
      <!--プロフィールイメージを表示するためのコード。プロフィール画像を登録していない場合のfallbackもサイズ指定が必須-->
       <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100', class: "m-2 attachment user profile_image" %>
       <table class="table">
         <tbody>
           <tr></tr>
           <tr>
             <th class="text-white">名前</th>
             <th class="text-white"><%= @users.name %></th>
           </tr>
           <tr>
             <th class="text-white">プロフィール</th>
             <th class="text-white"><%= @users.introduction %></th>
           </tr>
         </tbody>
       </table>
       <div class="row">
         <%= link_to"",edit_user_path(@user), class:"fas fa-user-cog btn btn-outline-light btn-block" %>
       </div>
      <h2 class="mt-3">新規投稿</h2>
      <!--新規投稿フォームの作成-->
      <%= form_with model:@book, local:true do |f| %>
       <div class="form-group">
         <label>本の題名</label>
         <%= f.text_field :title %>
       </div>
       <div class="form-group">
         <label>本の感想</label>
         <%= f.text_area :body %>
       </div>
       <div class="form-group">
         <%= f.submit '投稿', class: "btn btn-success" %>
       </div>
       <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2><%= @users.name %>の投稿</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th class="text-white">題名</th>
            <th class="text-white">感想</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
            <!--そのユーザーの投稿一覧表示-->
          <% @books.each do |book| %>
            <tr>
              <td>
                  <!--ユーザー画像はuser_showへのリンク-->
                <%= link_to user_path(@users.id) do %>

                 <%= attachment_image_tag @users, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "m-2 attachment user profile_image" %>
                <% end %>
              </td>
              <!--タイトルはbook_showのリンク-->
              <td class="text-white"><%= link_to book.title,book_path(book.id) %></td>
              <td class="text-white"><%= book.body %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>